# Generated by Django 2.2.4 on 2019-09-03 16:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Blog',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=250, verbose_name='Basliq')),
                ('desc', models.TextField(verbose_name='Metini daxil edin')),
                ('status', models.BooleanField(default=True, verbose_name='Status')),
                ('view_count', models.PositiveIntegerField(default=0, verbose_name='Baxis sayi')),
                ('images', models.ImageField(blank=True, null=True, upload_to='blog', verbose_name='Sekil')),
            ],
            options={
                'verbose_name': 'Blog',
                'verbose_name_plural': 'Blogs',
            },
        ),
        migrations.CreateModel(
            name='News',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=250, verbose_name='Title')),
                ('desc', models.TextField(verbose_name='Metini daxil edin')),
                ('status', models.BooleanField(default=True, verbose_name='Status')),
                ('view_count', models.PositiveIntegerField(default=0, verbose_name='Baxis sayi')),
                ('cover', models.ImageField(blank=True, null=True, upload_to='news', verbose_name='Cover Image')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updata_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'News',
                'verbose_name_plural': 'Newss',
            },
        ),
        migrations.CreateModel(
            name='PhoneCategory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Name')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('update_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='PhoneColor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Name')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('update_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='ProductsAttribute',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='name')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('update_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='ProductsClass',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='name')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('update_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Xiomi',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=250, verbose_name='Model')),
                ('desc', models.TextField(verbose_name='Xususiyyetler')),
                ('des', models.TextField(verbose_name='1')),
                ('de', models.TextField(verbose_name='2')),
                ('d', models.TextField(verbose_name='3')),
                ('price', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='Price')),
                ('view_count', models.PositiveIntegerField(default=0, verbose_name='Baxis sayi')),
                ('cover', models.ImageField(blank=True, null=True, upload_to='xiomi', verbose_name='Cover Image')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updata_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Xiomi',
                'verbose_name_plural': 'Xiomis',
            },
        ),
        migrations.CreateModel(
            name='Products',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=250, verbose_name='Basliq')),
                ('desc', models.TextField(verbose_name='Metni daxil edin')),
                ('upc', models.CharField(max_length=15, unique=True, verbose_name='UPC')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('update_at', models.DateTimeField(auto_now=True)),
                ('fk', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='products_attribute', to='core.ProductsAttribute')),
                ('sinif', models.ManyToManyField(blank=True, related_name='products_class', to='core.ProductsClass')),
            ],
        ),
        migrations.CreateModel(
            name='Phone',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=250, verbose_name='Basliq')),
                ('type', models.PositiveIntegerField(choices=[(1, '32GB'), (2, '64GB')], default=1, verbose_name='yaddas')),
                ('desc', models.TextField(verbose_name='Metni daxil edin')),
                ('upc', models.CharField(max_length=15, unique=True, verbose_name='UPC')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('update_at', models.DateTimeField(auto_now=True)),
                ('color', models.ManyToManyField(blank=True, related_name='phone_color', to='core.PhoneColor')),
                ('fk', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='phone_category', to='core.PhoneCategory')),
            ],
        ),
    ]
