# Generated by Django 2.2.4 on 2019-09-05 16:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_sides'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sides',
            name='url',
            field=models.URLField(max_length=50, verbose_name='URL'),
        ),
    ]
